
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clfvypqxfbmdytnmzsga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsZnZ5cHF4ZmJtZHl0bm16c2dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTM4MjYsImV4cCI6MjA2MDIyOTgyNn0.RZx_fWAe-RyZHeATThsUaPB8NDaBpR93v729vUAgigw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
//
// Example usage:
// - Query data: const { data, error } = await supabase.from('table_name').select('*')
// - Insert data: const { data, error } = await supabase.from('table_name').insert([{ column: value }])
// - Update data: const { data, error } = await supabase.from('table_name').update({ column: value }).eq('id', id)
// - Delete data: const { data, error } = await supabase.from('table_name').delete().eq('id', id)
// - Listen to realtime changes: 
//   const channel = supabase.channel('table-changes').on('postgres_changes', { event: '*', schema: 'public' }, callback).subscribe()

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
